In [2]:
# scikit-mcda
# https://pypi.org/project/scikit-mcda/

In [3]:
from scikitmcda.topsis import TOPSIS
from scikitmcda.wsm import WSM
from scikitmcda.wpm import WPM
from scikitmcda.waspas import WASPAS
from scikitmcda.promethee_ii import PROMETHEE_II
from scikitmcda.electre_i import ELECTRE_I
from scikitmcda.electre_ii import ELECTRE_II
from scikitmcda.vikor import VIKOR
from scikitmcda.constants import MAX, MIN, LinearMinMax_, LinearMax_, LinearSum_, Vector_, EnhancedAccuracy_, Logarithmic_
from sklearn.preprocessing import normalize

In [7]:
topsis = TOPSIS()

topsis.dataframe([[250, 16, 12, 5],
                  [200, 16,  8, 3],
                  [300, 32, 16, 4],
                  [275, 32,  8, 4],
                  [225, 16,  16, 2]],
                 ["Mobile 1", "Mobile 2", "Mobile 3", "Mobile 4", "Mobile 5"],
                 ["COST", "STORAGE", "CAMERA", "DESIGN"]
                 )
print(topsis.pretty_original())

+----+----------------+--------+-----------+----------+----------+
|    | alternatives   |   COST |   STORAGE |   CAMERA |   DESIGN |
|----+----------------+--------+-----------+----------+----------|
|  0 | Mobile 1       |    250 |        16 |       12 |        5 |
|  1 | Mobile 2       |    200 |        16 |        8 |        3 |
|  2 | Mobile 3       |    300 |        32 |       16 |        4 |
|  3 | Mobile 4       |    275 |        32 |        8 |        4 |
|  4 | Mobile 5       |    225 |        16 |       16 |        2 |
+----+----------------+--------+-----------+----------+----------+


In [21]:
# topsis.set_weights_manually([0.5918, 0.2394, 0.1151, 0.0537])
# topsis.set_weights_by_entropy()
# topsis.set_weights_by_ranking_B_POW(0)

                                   # C1   C2     C3   C4
#w_AHP = topsis.set_weights_by_AHP([[  1,    4,    5,   7],   # C1
#                                   [1/4,    1,    3,   5],   # C2
#                                   [1/5,  1/3,    1,   3],   # C3
#                                   [1/7,  1/5,  1/3,   1]])  # C4
weight_AHP = [[  1,    1/5,    1/5],
               [5,    1,    1/3],
               [5, 3,    1]]
w_AHP = topsis.set_weights_by_AHP(weight_AHP)  # C4

z = normalize(weight_AHP, axis=0)
print(z)

print("AHP Returned:\n", w_AHP)

topsis.set_signals([MIN, MAX, MAX, MAX])
topsis.decide()

[[0.14002801 0.06311944 0.18641093]
 [0.70014004 0.3155972  0.31068488]
 [0.70014004 0.9467916  0.93205465]]
AHP Returned:
 {'consistency': False, 'lambda': 3.1377648412790844, 'CIndex': 0.0688824206395422, 'CRatio': 0.11876279420610725}


ValueError: Unable to coerce to Series, length must be 4: given 3

In [22]:
weight_AHP = [[  1,    1/5,    1/5],
              [5,    1,    1/2],
              [5, 2,    1]]
w_AHP = topsis.set_weights_by_AHP(weight_AHP)  # C4

z = normalize(weight_AHP, axis=0)
print(z)

print("AHP Returned:\n", w_AHP)
print("AHP Returned:\n", topsis.weights)

topsis.set_signals([MIN, MAX, MAX, MAX])
topsis.decide()

[[0.14002801 0.08908708 0.17609018]
 [0.70014004 0.4454354  0.44022545]
 [0.70014004 0.89087081 0.88045091]]
AHP Returned:
 {'consistency': True, 'lambda': 3.053908656171728, 'CIndex': 0.026954328085863954, 'CRatio': 0.04647297945838613}
AHP Returned:
 [0.09035204991087344, 0.3537210338680927, 0.555926916221034]


ValueError: Unable to coerce to Series, length must be 4: given 3

In [6]:
print("WEIGHTS:\n", topsis.weights)

WEIGHTS:
 [0.5809771356405764, 0.2429005339101441, 0.12011108977871769, 0.056011240670561804]


In [20]:
print("NORMALIZED:\n", topsis.pretty_normalized())

NORMALIZED:
 +----+----------------+----------+-----------+----------+----------+
|    | alternatives   |     COST |   STORAGE |   CAMERA |   DESIGN |
|----+----------------+----------+-----------+----------+----------|
|  0 | Mobile 1       | 0.442807 |  0.301511 | 0.428571 | 0.597614 |
|  1 | Mobile 2       | 0.354246 |  0.301511 | 0.285714 | 0.358569 |
|  2 | Mobile 3       | 0.531369 |  0.603023 | 0.571429 | 0.478091 |
|  3 | Mobile 4       | 0.487088 |  0.603023 | 0.285714 | 0.478091 |
|  4 | Mobile 5       | 0.398527 |  0.301511 | 0.571429 | 0.239046 |
+----+----------------+----------+-----------+----------+----------+


In [21]:
print("WEIGHTED:\n", topsis.pretty_weighted())

WEIGHTED:
 +----+----------------+-----------+-----------+----------+-----------+
|    | alternatives   |      COST |   STORAGE |   CAMERA |    DESIGN |
|----+----------------+-----------+-----------+----------+-----------|
|  0 | Mobile 1       | 0.0290685 |  0.114011 | 0.123166 | 0.16066   |
|  1 | Mobile 2       | 0.0232548 |  0.114011 | 0.082111 | 0.0963957 |
|  2 | Mobile 3       | 0.0348822 |  0.228022 | 0.164222 | 0.128528  |
|  3 | Mobile 4       | 0.0319753 |  0.228022 | 0.082111 | 0.128528  |
|  4 | Mobile 5       | 0.0261616 |  0.114011 | 0.164222 | 0.0642638 |
+----+----------------+-----------+-----------+----------+-----------+


In [22]:
print("RANKING TOPSIS with", topsis.normalization_method , ":\n", topsis.pretty_decision())

RANKING TOPSIS with Vector :
 +----+----------------+---------------------+--------+
|    | alternatives   |   performance score |   rank |
|----+----------------+---------------------+--------|
|  0 | Mobile 1       |            0.463799 |      3 |
|  1 | Mobile 2       |            0.181113 |      5 |
|  2 | Mobile 3       |            0.818887 |      1 |
|  3 | Mobile 4       |            0.596357 |      2 |
|  4 | Mobile 5       |            0.356068 |      4 |
+----+----------------+---------------------+--------+


In [23]:
topsis.decide(EnhancedAccuracy_)
print("RANKING TOPSIS with", topsis.normalization_method, ":\n", topsis.pretty_decision())

RANKING TOPSIS with EnhancedAccuracy :
 +----+----------------+---------------------+--------+
|    | alternatives   |   performance score |   rank |
|----+----------------+---------------------+--------|
|  0 | Mobile 1       |            0.481891 |      3 |
|  1 | Mobile 2       |            0.19915  |      5 |
|  2 | Mobile 3       |            0.80085  |      1 |
|  3 | Mobile 4       |            0.546128 |      2 |
|  4 | Mobile 5       |            0.405637 |      4 |
+----+----------------+---------------------+--------+


In [14]:
import numpy as np

def create_upper_matrix(values, size):
    upper = np.zeros((size, size))
    upper[np.triu_indices(3, 0)] = values
    return(upper)

c = create_upper_matrix([1, 2, 3, 4, 5, 6], 3)
print(c)

[[1. 2. 3.]
 [0. 4. 5.]
 [0. 0. 6.]]


In [23]:
x = np.arange(100, 116).reshape(4,4)
print(x)
y = np.arange(16)
print(np.diag([1,1,1,1]))

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
